from enum import Enum

class DamageEnum(Enum):
    NONE = 0
    MIN = 1
    MAX = 2

class HeroSkillLevel(Enum):
    BASIC = 1
    ADVANCED = 2
    EXPERT = 3

class HeroSpecialization(Enum):
    ARCHERY = 1 # Orrin
    OFFENSE = 2 # Gundula and Crag Hack
    ARMORER = 3 # Mephala, Neela and Tazar

class SpecialAdditives(Enum):
    FORTUNE = 0
    CAVALIER_AND_CHAMPION_HEX = 1
    BLESS_SPELL = 2
    BLESS_SPELL_WITH_WATER_MAGIC_AT_LEAST_AT_ADVANCED_LEVEL = 3
    DEATHBLOW_OF_THE_DREAD_KNIGHT = 4
    CURSE_SPELL = 5
    CURSE_SPELL_WITH_FIRE_MAGIC_AT_LEAST_AT_ADVANCED_LEVEL = 6
    SHOT_WITH_A_BROKEN_ARROW = 7
    RANGED_UNIT_AT_MELEE_ATTACK = 8
    ARTIFACT___BOW_OF_ELVEN_CHERRYWOOD___5_PERCENT = 9
    ARTIFACT___BOWSTRING_OF_THE_UNICORNS_MANE___10_PERCENT = 10
    ARTIFACT___ANGEL_FEATHER_ARROWS___15_PERCENT = 11
    SHIELD_SPELL = 12
    SHIELD_SPELL_WITH_EARTH_MAGIC_AT_LEAST_AT_ADVANCED_LEVEL = 13
    AIR_SHIELD_SPELL = 14
    AIR_SHIELD_SPELL_WITH_AIR_MAGIC_AT_LEAST_AT_ADVANCED_LEVEL = 15
